### ISSUE TITLE
Show filters, Add rule, Negate rule: not every rule displays that it is a negated rule 

### ISSUE THREAD

**Issue by brita-sed** [geryxyz/iFL4Eclipse#207]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project.
1. Click iFL button. 
1. Load scores. 
1. Show filters. 
1. At Filters tab click Add rule button. 
1. Add different normal and negated rules. 

**Expected results**
* If the user negates a rule, it is displayed on the widget of the rule. 

**Received results**
* Displayed: Name, Signature, Parent type, Path
* Not displayed: Score, Last action, Context size, Position, Interactivity

![negated_rule](https://user-images.githubusercontent.com/16755484/118109523-9db79600-b3e1-11eb-9c55-42f37ab2a47b.jpg)

**Environment:**
* Package: https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V3.0.0.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V3.0.207.1

**Comment by brita-sed** [comment]
Negation has been corrected. 

![negate_corrected](https://user-images.githubusercontent.com/16755484/118271301-5d2f4980-b4c1-11eb-96dc-c651f18b237a.jpg)
