### ISSUE TITLE
Show filters, Add rule, interactivity rules: icons were swapped

### ISSUE THREAD

**Issue by brita-sed** [geryxyz/iFL4Eclipse#208]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project.
1. Click iFL button. 
1. Load scores. 
1. Show filters. 
1. At Filters tab click Add rule button. 
1. Choose Interactivity.
1. Add different rules: negate rule and with true/false conditon. 

**Expected results**
* The icons on the widget of the rule appears correctly. 

**Received results**
* The icons of interactive and not interactive were swapped. 

![icons_swapped](https://user-images.githubusercontent.com/16755484/118110026-3221f880-b3e2-11eb-897d-cdba0ec5f673.jpg)

**Environment:**
* Package: https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V3.0.0.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V3.0.207.1

**Comment by brita-sed** [comment]
This bug has been corrected, I think the negation is also good. 

![corrected_icos](https://user-images.githubusercontent.com/16755484/118270640-9f0bc000-b4c0-11eb-9e5c-0dc3597aa00e.jpg)
