### ISSUE TITLE
java.lang.UnsupportedOperationException while filtering in case of undefined elements

### ISSUE THREAD

**Issue by brita-sed** [geryxyz/iFL4Eclipse#210]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project.
1. Click iFL button. 
1. In the generated csv file delete some rows. 
1. Load scores -> load this modified csv. 
1. Click Hide undefined button to show undefined scored elements. 
1. Select some element. 
1. Click "Show ordering list" button. 
1. Move attributes to the right table. 
1. Close iFL tab. 

**Expected results**
* Sorting undefined elements works correctly (or when there are undefined elements, soring is inactive). 

**Received results**
* Attributes which I moved "disappear": they didn't appear in the right table. 
* ![unsupported_sorting_1](https://user-images.githubusercontent.com/16755484/118151606-16cfe100-b414-11eb-8362-17304f540243.jpg)

* Error in log: 
[unsupported_sorting_log.txt](https://github.com/InteractiveFaultLocalization/iFL4Eclipse/files/6473595/unsupported_sorting_log.txt)

!ENTRY org.eclipse.ui.workbench 4 2 2021-05-13 17:48:36.088
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
```
java.lang.UnsupportedOperationException
	at org.eclipse.sed.ifl.util.wrapper.Defineable.getValue(Defineable.java:18)
	at org.eclipse.sed.ifl.ide.gui.element.SelectedElementUI.originChanged(SelectedElementUI.java:198)
	at org.eclipse.sed.ifl.ide.gui.ScoreListUI.contentsChanged(ScoreListUI.java:436)
	at org.eclipse.sed.ifl.ide.gui.ScoreListUI.setMethodScore(ScoreListUI.java:422)
	at org.eclipse.sed.ifl.view.ScoreListView.refreshScores(ScoreListView.java:41)
	at org.eclipse.sed.ifl.control.score.ScoreListControl.refreshView(ScoreListControl.java:407)
	at org.eclipse.sed.ifl.control.score.ScoreListControl.lambda$11(ScoreListControl.java:392)
```
* Error message in UI after closing iFL tab: 
![unsopported_sorting](https://user-images.githubusercontent.com/16755484/118151632-1e8f8580-b414-11eb-9639-de0b67bc7e02.JPG)

**Related issues:**
* #200 Unhandled event loop exception, UnsupportedOperationException applying a rule with undefined scored elements

**Environment:**
* Package: https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V3.0.0.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/InteractiveFaultLocalization/iFL4Eclipse/releases/tag/V3.0.210.1

**Comment by brita-sed** [comment]
The bug has been corrected: 

![undefined_soring_corrected](https://user-images.githubusercontent.com/16755484/118248591-c359a380-b4a4-11eb-839c-7b18353c9c09.jpg)
